package gui;

import javax.swing.JOptionPane;
import repositorios.R_Registro;
import conectores.Conexion;
import java.sql.Connection;
import java.sql.SQLException;

public class PanelPrincipalClientes extends javax.swing.JFrame {
private Connection connection;
private String usurnameIngresado;
private String passwordIngresado;
   public PanelPrincipalClientes() {
        initComponents();        
            // Puedes manejar el error de conexión aquí, como mostrar un mensaje de error.
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jTextUsurname = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JButton btnLogin = new javax.swing.JButton();
        javax.swing.JButton btnCrearCuenta = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("CLIENTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 180, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usurname");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 110, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jTextUsurname.setBackground(new java.awt.Color(0, 0, 0));
        jTextUsurname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextUsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono Tesla.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("SIGN IN ");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 160, 40));

        btnCrearCuenta.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("CREATE ACCOUNT");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 160, 40));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 242, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de Pantalla.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        
        PanelRegistrarse pr = new PanelRegistrarse();
        pr.setSize(1000, 700);
        pr.setVisible(true);
        pr.setLocationRelativeTo(null);
        pr.setTitle("CREAR CUENTA ");
        
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code 
      String usurnameIngresado = jTextUsurname.getText();
    String passwordIngresado = jPasswordField1.getText();
    if (usurnameIngresado.isEmpty() || passwordIngresado.isEmpty()) {
        // Mostrar un mensaje de error si los campos están vacíos
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre de usuario y una contraseña válidos.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        return;
    }
 
    R_Registro con = new R_Registro(connection);
    
    // Llama al método consultarRegistro solo una vez
    boolean contraseñaCorrecta = con.consultarRegistro(usurnameIngresado, passwordIngresado);
    
    
    if (contraseñaCorrecta) {
        // La contraseña es correcta, mostrar la ventana final
        VentanaFinal vf = new VentanaFinal(usurnameIngresado, passwordIngresado);
        vf.setVisible(true);
        vf.setLocationRelativeTo(null);
        vf.setSize(1000, 730);
        vf.setTitle("ASEGURADORA POO");
    } else {
        // Mostrar un mensaje de error si la autenticación falla
        JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
    }  
    // Supongamos que tienes un JTextField llamado "textField"

// Para borrar el contenido del JTextField:
jTextUsurname.setText("");
jPasswordField1.setText("");

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextUsurname;
    // End of variables declaration//GEN-END:variables
}
