
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import conectores.Conexion;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class VentanaFinal extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
private String usurnameIngresado;
private String passwordIngresado;
    public VentanaFinal(String username, String password) {
        try {
            initComponents();
            txtSeguro.setEditable(false);
            txtNombre.setEditable(false);
            txtApellido.setEditable(false);
            txtAuto.setEditable(false);
            txtAño.setEditable(false);
            txtDireccion.setEditable(false);
            txtMatricula.setEditable(false);
            txtModelo.setEditable(false);
            txtValor.setEditable(false);
            jTabbedPane1.setSelectedIndex(3);
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setSelectedIndex(3);
            conn = Conexion.obtenerConnection();
            this.usurnameIngresado = username;
            this.passwordIngresado = password;
        } catch (SQLException e) {
            // Maneja la excepción aquí, por ejemplo, muestra un mensaje de error o registra el problema.
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JButton btnInicioo = new javax.swing.JButton();
        javax.swing.JButton btnInformaccion = new javax.swing.JButton();
        javax.swing.JButton btnCarro = new javax.swing.JButton();
        javax.swing.JButton btnSeguro = new javax.swing.JButton();
        javax.swing.JButton btnInicio = new javax.swing.JButton();
        javax.swing.JButton btnCerrarSesion = new javax.swing.JButton();
        javax.swing.JButton btnAuto = new javax.swing.JButton();
        javax.swing.JButton btnInformacion = new javax.swing.JButton();
        javax.swing.JButton btnSeguros1 = new javax.swing.JButton();
        javax.swing.JButton btnCerrar = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel25 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel26 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel27 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel28 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel29 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel31 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel32 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel33 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel34 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel35 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel36 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel37 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel38 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel39 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel40 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel41 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel42 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel43 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtSeguro = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAuto = new javax.swing.JTextField();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 230, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ASEGURADORA POO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono Tesla Rojo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCuadrado.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 190));

        btnInicioo.setBackground(new java.awt.Color(240, 230, 255));
        btnInicioo.setForeground(new java.awt.Color(240, 230, 255));
        btnInicioo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono Boton Inicio.png"))); // NOI18N
        btnInicioo.setBorderPainted(false);
        btnInicioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciooActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, 70));

        btnInformaccion.setBackground(new java.awt.Color(240, 230, 255));
        btnInformaccion.setForeground(new java.awt.Color(240, 230, 255));
        btnInformaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono Persona vf.png"))); // NOI18N
        btnInformaccion.setBorderPainted(false);
        btnInformaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformaccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInformaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 70, 60));

        btnCarro.setBackground(new java.awt.Color(240, 230, 255));
        btnCarro.setForeground(new java.awt.Color(240, 230, 255));
        btnCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono carro vf.png"))); // NOI18N
        btnCarro.setBorderPainted(false);
        btnCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 80, 50));

        btnSeguro.setBackground(new java.awt.Color(240, 230, 255));
        btnSeguro.setForeground(new java.awt.Color(240, 230, 255));
        btnSeguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono seguros vf.png"))); // NOI18N
        btnSeguro.setBorderPainted(false);
        btnSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguroActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 550, 60, 60));

        btnInicio.setBackground(new java.awt.Color(240, 230, 255));
        btnInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnInicio.setText("inicio     ");
        btnInicio.setBorderPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 30));

        btnCerrarSesion.setBackground(new java.awt.Color(240, 230, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 180, 40));

        btnAuto.setBackground(new java.awt.Color(240, 230, 255));
        btnAuto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnAuto.setText("Auto      ");
        btnAuto.setBorderPainted(false);
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 160, 30));

        btnInformacion.setBackground(new java.awt.Color(240, 230, 255));
        btnInformacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnInformacion.setText("Informacion  ");
        btnInformacion.setBorderPainted(false);
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 170, 30));

        btnSeguros1.setBackground(new java.awt.Color(240, 230, 255));
        btnSeguros1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnSeguros1.setText("Seguro   ");
        btnSeguros1.setBorderPainted(false);
        btnSeguros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguros1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeguros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 160, 30));

        btnCerrar.setForeground(new java.awt.Color(240, 230, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono Cerrar Sesion.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Aplicacion arriba.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 110));

        jTabbedPane1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amplio");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 97, 42));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("AmplioPlus");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 42));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Basico");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 97, 42));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Premium");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 97, 42));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("●Se ofrecen las mismas coberturas que el de Responsabilidad Civil ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 380, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("●Robo total del auto. ");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 350, 20));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("●Auxilio vial si se te poncha una llanta\n necesitas gasolina o una grúa.");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 380, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("●Engloba seguro de responsabilidad civil y cobertura basica ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 330, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("●ademas de daños a tu auto como resultado de un accidente");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 330, 20));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("●Incluye todos los beneficios anterirormente mencionados ");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 330, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("el seguro de daños a terceros cubre los siguientes aspectos: ");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 320, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("●Daños provocados a los autos o pertenencias de terceras ");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 330, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("●Auxilio vial Ilimitados");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 260, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("●Daños a terceros sin seguro");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 260, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("●Afeccionas a tus llantas ");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 260, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("●Auto Sustituto en caso de que el vehiculo quede inutilizado");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 330, -1));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("●Incluye beneficios mencionados anteriormente ");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 260, -1));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("personas (casa, auto o negocio). ");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 300, 20));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("●Daños físicos o fallecimiento de otras personas.");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 310, 20));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("tengas un accidente mientras manejas un carro que no sea el tuyo. ");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 360, -1));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("●Reparaciones a los autos de otras personas en caso de que tengas");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 370, -1));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("de accidente");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 310, -1));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("●Servicios médicos para ti y las personas viajando en tu auto en caso ");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 390, -1));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("●Asistencia legal.");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 310, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de aplicacion vf.gif"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Modelo");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 277, 81, 44));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Matricula");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 73, 81, 44));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Valor");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 73, 81, 44));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Año");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 277, 81, 44));
        jPanel5.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 140, 40));
        jPanel5.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 140, 40));
        jPanel5.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 40));

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        jPanel5.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de aplicacion vf.gif"))); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 98, 90, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 98, 90, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Direccion");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 227, 90, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seguro");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 355, 90, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Auto");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 355, 90, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de nac");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, 30));

        txtApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 100, 127, 30));

        txtEdad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 229, 127, 30));

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 229, 127, 30));

        txtSeguro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 357, 127, 30));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, 127, 30));

        txtAuto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel3.add(txtAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 357, 127, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de aplicacion vf.gif"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de aplicacion vf.gif"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));

        jTabbedPane1.addTab("tab1", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 770, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformaccionActionPerformed
        // TODO add your handling code here:
           jTabbedPane1.setSelectedIndex(2);
       
    String sql ="SELECT c.nombre, c.apellido, c.direccion, c.FechaDeNacimiento, a.marca, s.nombredelseguro FROM clientes c inner JOIN autos a on c.id_cliente=a.id_auto inner join seguros s on c.id_cliente=s.id_seguros inner join registro r ON c.id_cliente = r.id_registro WHERE r.usurname = ? AND r.password = ?;";
         try{
  pst = conn.prepareStatement(sql);
        pst.setString(1, usurnameIngresado);
        pst.setString(2, passwordIngresado);
        rs = pst.executeQuery();

              if (rs.next()) {
                  String add1=rs.getString("nombre");
                  txtNombre.setText(add1);
                  String add2=rs.getString("apellido");
                  txtApellido.setText(add2);
                  String add3=rs.getString("FechaDeNacimiento");
                  txtEdad.setText(add3);
                  String add4=rs.getString("direccion");
                  txtDireccion.setText(add4);
                  String add5=rs.getString("marca");
                  txtAuto.setText(add5);
                  String add6=rs.getString("nombredelseguro");
                  txtSeguro.setText(add6);
              }
              }catch(Exception e){
                      JOptionPane.showMessageDialog(null, e);
                  
                  
              }finally{
           try{
               rs.close();
               pst.close();
           }catch (Exception e){
               
           }
          }
    }//GEN-LAST:event_btnInformaccionActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(2);
       
    String sql ="SELECT c.nombre, c.apellido, c.direccion, c.FechaDeNacimiento, a.marca, s.nombredelseguro FROM clientes c inner JOIN autos a on c.id_cliente=a.id_auto inner join seguros s on c.id_cliente=s.id_seguros inner join registro r ON c.id_cliente = r.id_registro WHERE r.usurname = ? AND r.password = ?;";
         try{
  pst = conn.prepareStatement(sql);
        pst.setString(1, usurnameIngresado);
        pst.setString(2, passwordIngresado);
        rs = pst.executeQuery();

              if (rs.next()) {
                  String add1=rs.getString("nombre");
                  txtNombre.setText(add1);
                  String add2=rs.getString("apellido");
                  txtApellido.setText(add2);
                  String add3=rs.getString("FechaDeNacimiento");
                  txtEdad.setText(add3);
                  String add4=rs.getString("direccion");
                  txtDireccion.setText(add4);
                  String add5=rs.getString("marca");
                  txtAuto.setText(add5);
                  String add6=rs.getString("nombredelseguro");
                  txtSeguro.setText(add6);
              }
              }catch(Exception e){
                      JOptionPane.showMessageDialog(null, e);
                  
                  
              }finally{
           try{
               rs.close();
               pst.close();
           }catch (Exception e){
               
           }
          }
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);

    // Consultar la información del auto asociado al cliente
    String sql = "SELECT a.matricula, a.valor, a.ano, a.modelo " +
                 "FROM autos a " +
                 "INNER JOIN clientes c ON a.id_auto = c.id_cliente " +
                 "INNER JOIN registro r ON c.id_cliente = r.id_registro " +
                 "WHERE r.usurname = ? AND r.password = ?;";

    try {
        pst = conn.prepareStatement(sql);
        pst.setString(1, usurnameIngresado);
        pst.setString(2, passwordIngresado);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Mostrar la información del auto
            String add1 = rs.getString("matricula");
            txtMatricula.setText(add1);

            String add2 = rs.getString("valor");
            txtValor.setText(add2);

            String add3 = rs.getString("ano");
            txtAño.setText(add3);

            String add4 = rs.getString("modelo");
            txtModelo.setText(add4);
        } else {
            // Si no se encontró información, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "No se encontró información para este usuario.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {
            // Manejo de errores
        }
    }
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguroActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnSeguroActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnIniciooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciooActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnIniciooActionPerformed

    private void btnCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);

    // Consultar la información del auto asociado al cliente
    String sql = "SELECT a.matricula, a.valor, a.ano, a.modelo " +
                 "FROM autos a " +
                 "INNER JOIN clientes c ON a.id_auto = c.id_cliente " +
                 "INNER JOIN registro r ON c.id_cliente = r.id_registro " +
                 "WHERE r.usurname = ? AND r.password = ?;";

    try {
        pst = conn.prepareStatement(sql);
        pst.setString(1, usurnameIngresado);
        pst.setString(2, passwordIngresado);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Mostrar la información del auto
            String add1 = rs.getString("matricula");
            txtMatricula.setText(add1);

            String add2 = rs.getString("valor");
            txtValor.setText(add2);

            String add3 = rs.getString("ano");
            txtAño.setText(add3);

            String add4 = rs.getString("modelo");
            txtModelo.setText(add4);
        } else {
            // Si no se encontró información, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "No se encontró información para este usuario.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {
            // Manejo de errores
        }
    }
    }//GEN-LAST:event_btnCarroActionPerformed

    private void btnSeguros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguros1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnSeguros1ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAuto;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeguro;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
